defmodule App.Repo.Migrations.InitialMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :title, :text, null: false
      add :subtitle, :text
      add :description, :text
      add :tags, {:array, :text}, default: []
      add :links, {:array, :map}, default: []
      add :image, :text
    end
  end

  def down do
    drop table(:projects)
  end
end
