name: FreeBSD CD [build]

on:
  pull_request:
    branches: ["main"]

env:
  MIX_ENV: prod

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: freebsd 13.2 VM
        uses: cross-platform-actions/action@v0.15.0
        with:
          operating_system: freebsd
          version: "13.2"
          shell: bash
          environment_variables: MIX_ENV
          run: |
            uname -a
            echo $SHELL
            pwd
            ls -lah
            whoami
            sudo pkg update
            env | sort
